/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tab)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tab)'}/courses` | `/courses`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tab)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tab)'}/settings/profile` | `/settings/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tab)'}/courses/[id]` | `/courses/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tab)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tab)'}/courses` | `/courses`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tab)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tab)'}/settings/profile` | `/settings/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tab)'}/courses/[id]` | `/courses/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tab)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(tab)'}/courses${`?${string}` | `#${string}` | ''}` | `/courses${`?${string}` | `#${string}` | ''}` | `${'/(tab)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `${'/(tab)'}/settings/profile${`?${string}` | `#${string}` | ''}` | `/settings/profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tab)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tab)'}/courses` | `/courses`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tab)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tab)'}/settings/profile` | `/settings/profile`; params?: Router.UnknownInputParams; } | `${'/(tab)'}/courses/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/courses/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `${'/(tab)'}/courses/[id]` | `/courses/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
